CREATE DATABASE lab10;
GO
USE lab10;
CREATE TABLE Students
(
    Id INT IDENTITY PRIMARY KEY,
    StudentsName NVARCHAR(300) NOT NULL,
    StudentsSurname NVARCHAR(200) NOT NULL,
    Age INT DEFAULT 0,
    Place NVARCHAR(200), 
);
CREATE TABLE Uni 
(
    Id INT IDENTITY PRIMARY KEY,
    StudentsId INT NOT NULL,
    Fakultet NVARCHAR(600) NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
);
